name: mlops-test
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - 'main'

jobs:
  train-model-ci:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Decode and recreate service account JSON
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > service_account.json

      - name: Train model
        env:
          SERVICE_ACCOUNT_FILE: './service_account.json'
          FOLDER_ID: ${{ secrets.MODEL_SAVE_FOLDER_ID }}  # Replace with your actual folder ID or store in a GitHub secret
        run: |
          python train_model.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Report metrics
          echo "## Result" >> report.md
          cat results.txt >> report.md

          # Report training history
          echo "## Plots\n### Training Loss VS Val Loss" >> report.md
          echo '![](./plot.png)' >> report.md
          cml comment create report.md

  validate-model-ci:
    needs: train-model-ci
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Decode and recreate service account JSON
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > service_account.json

      - name: Test model
        env:
          SERVICE_ACCOUNT_FILE: './service_account.json'
        run: |
          python testing.py

      - name: Write Testing report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Report result test
          echo "## Test Result" >> report.md
          cat test_result.txt >> report.md

          # Report testing history
          echo "## Plots\n### Prediction VS Actual plot" >> report.md
          echo '![](./plot_prediction.png)' >> report.md
          cml comment create report.md