name: mlops-test
on: [push]
jobs:
  train-model-ci:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train_model.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Report metrics
          echo "## Result" >> report.md
          cat results.txt >> report.md

          # Report training history
          echo -e "## Plots\n### Training History" >> report.md
          echo '![](./plot.png)' >> report.md
          cml comment create report.md